import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TableModule } from 'primeng/table';
import { ButtonModule } from 'primeng/button';
import { SelectModule } from 'primeng/select';
import { TagModule } from 'primeng/tag';
import { InputTextModule } from 'primeng/inputtext';

interface Report {
  id: number;
  name: string;
  type: string;
  generatedBy: string;
  date: string;
  status: 'Ready' | 'Processing' | 'Failed';
  size: string;
}

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule, FormsModule, TableModule, ButtonModule, SelectModule, TagModule, InputTextModule],
  template: `
    <div class="page-header">
      <div>
        <h1>Reports</h1>
        <p>Generate and download operational reports</p>
      </div>
      <button pButton label="Export" icon="pi pi-download" class="p-button-success" (click)="exportCSV()"></button>
    </div>

    <div class="stats-grid">
      @for (stat of stats; track stat.label) {
        <div class="stat-card">
          <div class="stat-icon" [style.background]="stat.color + '20'" [style.color]="stat.color">
            <i [class]="stat.icon"></i>
          </div>
          <div class="stat-info">
            <span class="stat-value">{{ stat.value }}</span>
            <span class="stat-label">{{ stat.label }}</span>
          </div>
        </div>
      }
    </div>

    <div class="table-toolbar">
      <div class="search-box">
        <i class="pi pi-search"></i>
        <input type="text" pInputText placeholder="Search reports..." [(ngModel)]="searchTerm" />
      </div>
      <p-select [(ngModel)]="typeFilter" [options]="typeOptions" placeholder="All Types" [showClear]="true" style="min-width:160px" />
    </div>

    <div class="card-container">
      <p-table [value]="filteredReports()" [paginator]="true" [rows]="10" [showCurrentPageReport]="true" currentPageReportTemplate="Showing {first} to {last} of {totalRecords} reports">
        <ng-template #header>
          <tr>
            <th>Report Name</th>
            <th>Type</th>
            <th>Generated By</th>
            <th>Date</th>
            <th>Status</th>
            <th>Size</th>
            <th style="width:80px">Download</th>
          </tr>
        </ng-template>
        <ng-template #body let-r>
          <tr>
            <td>
              <div class="report-name">
                <i class="pi pi-file" style="color: var(--geidea-green)"></i>
                <span class="name-text">{{ r.name }}</span>
              </div>
            </td>
            <td><span class="type-badge">{{ r.type }}</span></td>
            <td>{{ r.generatedBy }}</td>
            <td class="date-text">{{ r.date }}</td>
            <td><p-tag [value]="r.status" [severity]="getStatusSeverity(r.status)" /></td>
            <td>{{ r.size }}</td>
            <td>
              @if (r.status === 'Ready') {
                <button pButton icon="pi pi-download" class="p-button-text p-button-success p-button-sm" (click)="downloadReport(r)"></button>
              }
            </td>
          </tr>
        </ng-template>
      </p-table>
    </div>
  `,
  styles: [`
    .page-header {
      display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 1.5rem;
      h1 { font-size: 1.5rem; font-weight: 700; color: var(--text-primary); }
      p { font-size: 0.875rem; color: var(--text-secondary); margin-top: 0.25rem; }
    }
    .stats-grid {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; margin-bottom: 1.5rem;
    }
    .stat-card {
      background: var(--card-bg); border: 1px solid var(--border-color); border-radius: 12px; padding: 1.25rem;
      display: flex; align-items: center; gap: 1rem;
    }
    .stat-icon {
      width: 48px; height: 48px; border-radius: 12px; display: flex; align-items: center; justify-content: center;
      i { font-size: 1.25rem; }
    }
    .stat-value { font-size: 1.5rem; font-weight: 700; color: var(--text-primary); display: block; }
    .stat-label { font-size: 0.75rem; color: var(--text-secondary); }
    .table-toolbar { display: flex; gap: 1rem; margin-bottom: 1rem; align-items: center; flex-wrap: wrap; }
    .search-box {
      position: relative; max-width: 320px; flex: 1;
      i { position: absolute; left: 12px; top: 50%; transform: translateY(-50%); color: var(--text-secondary); }
      input { width: 100%; padding-left: 2.5rem; }
    }
    .card-container { background: var(--card-bg); border: 1px solid var(--border-color); border-radius: 12px; overflow: hidden; }
    .report-name { display: flex; align-items: center; gap: 0.6rem; }
    .name-text { font-weight: 600; font-size: 0.875rem; }
    .type-badge {
      background: color-mix(in srgb, var(--geidea-green) 12%, var(--card-bg));
      color: var(--geidea-green); padding: 3px 10px; border-radius: 6px; font-size: 0.75rem; font-weight: 600;
    }
    .date-text { font-size: 0.8rem; color: var(--text-secondary); }
  `]
})
export class ReportsComponent {
  searchTerm = '';
  typeFilter: string | null = null;
  typeOptions = ['Transaction', 'Settlement', 'Merchant', 'Compliance'];

  stats = [
    { label: 'Total Reports', value: '156', icon: 'pi pi-file', color: '#3bb54a' },
    { label: 'This Month', value: '23', icon: 'pi pi-calendar', color: '#3b82f6' },
    { label: 'Processing', value: '3', icon: 'pi pi-spin pi-spinner', color: '#f59e0b' },
    { label: 'Avg. Size', value: '2.4 MB', icon: 'pi pi-database', color: '#8b5cf6' }
  ];

  reports = signal<Report[]>([
    { id: 1, name: 'Monthly Transaction Summary - June', type: 'Transaction', generatedBy: 'Ahmed Al-Rashid', date: '2025-06-15', status: 'Ready', size: '3.2 MB' },
    { id: 2, name: 'Settlement Reconciliation Q2', type: 'Settlement', generatedBy: 'Sara Mohammed', date: '2025-06-14', status: 'Ready', size: '5.1 MB' },
    { id: 3, name: 'Merchant Onboarding Report', type: 'Merchant', generatedBy: 'Omar Hassan', date: '2025-06-14', status: 'Processing', size: '-' },
    { id: 4, name: 'PCI Compliance Audit', type: 'Compliance', generatedBy: 'Fatima Al-Zahrani', date: '2025-06-13', status: 'Ready', size: '1.8 MB' },
    { id: 5, name: 'Daily Transaction Log - Jun 12', type: 'Transaction', generatedBy: 'System', date: '2025-06-12', status: 'Ready', size: '890 KB' },
    { id: 6, name: 'Failed Transactions Report', type: 'Transaction', generatedBy: 'Nora Al-Saud', date: '2025-06-12', status: 'Failed', size: '-' },
    { id: 7, name: 'Merchant Fee Analysis', type: 'Settlement', generatedBy: 'Ahmed Al-Rashid', date: '2025-06-11', status: 'Ready', size: '2.3 MB' },
    { id: 8, name: 'KYC Verification Status', type: 'Compliance', generatedBy: 'Sara Mohammed', date: '2025-06-10', status: 'Ready', size: '4.5 MB' }
  ]);

  filteredReports = computed(() => {
    let list = this.reports();
    const term = this.searchTerm.toLowerCase();
    if (term) {
      list = list.filter(r => r.name.toLowerCase().includes(term) || r.generatedBy.toLowerCase().includes(term));
    }
    if (this.typeFilter) {
      list = list.filter(r => r.type === this.typeFilter);
    }
    return list;
  });

  getStatusSeverity(status: string): "success" | "danger" | "warn" {
    switch (status) {
      case 'Ready': return 'success';
      case 'Failed': return 'danger';
      default: return 'warn';
    }
  }

  exportCSV(): void {
    const data = this.filteredReports();
    const headers = ['Report Name', 'Type', 'Generated By', 'Date', 'Status', 'Size'];
    const rows = data.map(r => [r.name, r.type, r.generatedBy, r.date, r.status, r.size]);
    const csv = [headers.join(','), ...rows.map(r => r.map(v => `"${v}"`).join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `reports_${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  downloadReport(r: Report): void {
    const content = `Report: ${r.name}\nType: ${r.type}\nGenerated: ${r.date}\nGenerated By: ${r.generatedBy}\nStatus: ${r.status}\n\n[This is a sample report file]`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${r.name.replace(/\s+/g, '_')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }
}
